# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

env:
  - TOX_ENV=py36-django-20
  - TOX_ENV=py35-django-20

services:
  - postgresql
addons:
  postgresql: "9.5"

cache: pip

before_script:
  - psql --version
  - psql -c 'create database test_db;' -U postgres


matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: python runtests.py
