# Generated by Django 2.0.2 on 2018-04-23 05:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveSmallIntegerField(choices=[(0, 'Open Exchange Rates')], help_text='Where the exchange data comes from')),
                ('base_currency', models.CharField(max_length=3)),
                ('rates', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['base_currency', '-last_updated_at'],
            },
        ),
    ]
