# Generated by Django 2.0.2 on 2018-04-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
