# Generated by Django 3.1.1 on 2020-09-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_currencies', '0002_auto_20180429_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rates',
            field=models.JSONField(default=dict),
        ),
    ]
