name: CI

on:
  push:
    branches:
      - master
    tags:
      - v** # Run on all version tags
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        django: ["3.2.16", "4.0.8", "4.1.5", "5.2.0"]
        exclude:
          # Excludes Python 3.11 for Django < 4.1
          - python: "3.11"
            django: "3.2.16"
          - python: "3.11"
            django: "4.0.8"
          # Exclude older Python versions for Django 5.2 (Django 5.2 requires Python 3.10+)
          - python: "3.8"
            django: "5.2.0"
          - python: "3.9"
            django: "5.2.0"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 1s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry config --local virtualenvs.in-project true
      - run: poetry install
      - run: pip install -U django==${{ matrix.django }}
      - run: PGPASSWORD=postgres psql -c 'create database test_db;' -U postgres -h localhost -p 5432
      - run: poetry run python runtests.py

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  publish:
    if: startsWith(github.event.ref, 'refs/tags')
    name: Publish Python 🐍 distribution 📦
    needs: tests
    runs-on: ubuntu-latest

    permissions:
      id-token: write # mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --repo "$GITHUB_REPOSITORY" \
            --title "$GITHUB_REF_NAME" \
            --draft \
            --notes "Release $GITHUB_REF_NAME"
      - name: Upload artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$GITHUB_REF_NAME" dist/* \
            --repo "$GITHUB_REPOSITORY"
