name: CI

on:
  push:
    branches:
      - master
    tags:
      - v** # Run on all version tags
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        django: ["3.2.16", "4.0.8", "4.1.5", "5.2.0"]
        exclude:
          # Excludes Python 3.11 for Django < 4.1
          - python: "3.11"
            django: "3.2.16"
          - python: "3.11"
            django: "4.0.8"
          # Exclude older Python versions for Django 5.2 (Django 5.2 requires Python 3.10+)
          - python: "3.8"
            django: "5.2.0"
          - python: "3.9"
            django: "5.2.0"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 1s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry config --local virtualenvs.in-project true
      - run: poetry install
      - run: pip install -U django==${{ matrix.django }}
      - run: PGPASSWORD=postgres psql -c 'create database test_db;' -U postgres -h localhost -p 5432
      - run: poetry run python runtests.py

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  publish:
    if: startsWith(github.event.ref, 'refs/tags')
    name: publish
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dj-currencies
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          body: |
            ## What's Changed
            * Added Django 5.2 support
            * Updated test configurations

            For full details, see [HISTORY.rst](HISTORY.rst)
